pay_app/urls.py
from django.urls import path
from . import views

app_name = 'pay_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('make-payment/', views.make_payment, name='make-payment'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('notifications/', views.notifications, name='notifications'),
    path('notification/<int:notification_id>/read/', views.notifications, name='notification'),
    path('accept-payment/<int:notification_id>/', views.accept_payment, name='accept-payment'),
    path('reject-payment/<int:notification_id>/', views.reject_payment, name='reject-payment'),
    path('success/', views.success, name='success'),
    path('request-payment/', views.request_payment, name='request-payment'),
    path('success/', views.success, name='success'),
    path('about/', views.about, name='about'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pay_app.urls')),
    path('api/', include('currency_conversion_api.urls'))
]

templates/about.html
{% extends 'base.html' %}

{% block title %}
    <title>About</title>
{% endblock %}

{% block content %}
    {% include 'side_nav.html' %}
    <div class="column is-5 ml-auto mr-auto">
        <p>
            This is a simple DjangoPay app that allows you to make and request for payments
        </p>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bulma/bulma.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/js/all.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    {% block title %}
    {% endblock %}
</head>
<body>
<div id="wrapper">
    <nav class="navbar" role="navigation" aria-label="main navigation" id="navbar">
        <div class="navbar-brand">
            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasic">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasic" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{% url 'pay_app:index' %}">
                    Home
                </a>

                <a class="navbar-item" href="{% url 'pay_app:make-payment' %}">
                    Make Payment
                </a>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        More
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'pay_app:request-payment' %}">
                            Request Payment
                        </a>
                        <a class="navbar-item" href="{% url 'pay_app:about' %}">
                            About
                        </a>
                    </div>
                </div>
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        {% if user.is_authenticated %}
                            <a href="{% url 'pay_app:logout' %}" class="button is-light">
                                <strong>Log Out</strong>
                            </a>
                        {% else %}
                            <a class="button is-primary" href="{% url 'pay_app:register' %}">
                                <strong>Sign up</strong>
                            </a>
                            <a class="button is-link" href="{% url 'pay_app:login' %}">
                                Log in
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <main class="columns">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer">
        <div class="content has-text-centered">
            <p>
                <strong>Website</strong> by <a href="https://www.linkedin.com/in/allan-bosire-13b066180/">Bosire
                Allan.</a> <small>This should be removed from the code</small>
                <span class="is-flex is-justify-content-center is-align-items-center gap-1">
                <a href="https://www.linkedin.com/in/allan-bosire-13b066180/">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="https://t.me/jinn_allan">
                    <i class="fab fa-telegram"></i>
                </a>
                <a href="mailto:bosireallan@outlook.com">
                    <i class="fas fa-envelope"></i>
                </a>
            </span>
            </p>
        </div>
    </footer>
</div>
<script src="{% static 'main.js' %}"></script>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}


{% block title %}
    <title>Dashboard</title>
{% endblock %}

{% block content %}
    {% include 'side_nav.html' %}
    <div class="column">
        <div class="row">
            <div class="section profile-heading">
                <div class="columns is-mobile is-multiline">
                    <div class="column is-2">
                      <span class="header-icon user-profile-image">
                        <img alt="" src="http://placehold.it/300x225">
                      </span>
                    </div>
                    <div class="column is-4-tablet is-10-mobile name">
                        <p>
                            <span class="title is-bold mt-6">{{ user.username }}</span>
                            <br>
                        </p>
                    </div>
                    <div class="column is-2-tablet is-4-mobile has-text-centered">
                        <p class="stat-val" id="balance">{{ user.balance }}</p>
                        <p class="stat-key">Balance {{ user.currency.code }} </p>
                    </div>
                    <div class="column is-2-tablet is-4-mobile has-text-centered">
                        <p class="stat-val">{{ user.get_transactions.count }}</p>
                        <p class="stat-key">Transactions</p>
                    </div>
                    <div class="column is-2-tablet is-4-mobile has-text-centered">
                        <p class="stat-val">{{ user.get_unread_notifications.count }}</p>
                        <p class="stat-key">Notifications</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="column">
                <div class="panel">
                    <div class="panel-heading">
                        Transactions
                    </div>
                    <div class="panel-block">
                        <p class="control has-icons-left">
                            <input class="input" type="text" placeholder="Search">
                        </p>
                    </div>
                    <div class="panel-block is-flex is-justify-content-center is-flex-direction-column">
                        <table class="table is-bordered is-striped is-truncated">
                            <thead>
                            <tr>
                                <th width="100">From</th>
                                <th width="100">To</th>
                                <th width="100">Amount</th>
                                <th width="350">Trace</th>
                                <th width="150">Date</th>
                                <th width="100">Status</th>
                                <th width="163">Disputed</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in transactions %}
                                <tr>
                                    <td>{{ item.money_from | capfirst }}</td>
                                    <td>{{ item.money_to | capfirst }}</td>
                                    <td data-uuid="{{ item.uuid }}">{{ item.amount }}</td>
                                    <td>{{ item.uuid }}</td>
                                    <td>{{ item.transaction_date }}</td>
                                    {% if item.status == True %}
                                        <td><span class="tag is-success">Success</span></td>
                                    {% else %}
                                        {% if item.committed == False %}
                                            <td><span class="tag is-danger">Failed</span></td>
                                        {% else %}
                                            <td><span class="tag is-warning">Pending</span></td>
                                        {% endif %}
                                    {% endif %}
                                    {% if item.committed == True %}
                                        <td><span class="tag is-info">No</span></td>
                                    {% else %}
                                        <td><span class="tag is-danger">Disputed</span></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <nav class="pagination is-centered" role="navigation" aria-label="pagination">
                            <a class="pagination-previous">Previous</a>
                            <a class="pagination-next">Next</a>
                            <ul class="pagination-list">
                                {% if transactions.has_previous %}
                                    <li><a class="pagination-link"
                                           href="?page={{ transactions.previous_page_number }}">Prev</a></li>
                                {% endif %}
                                <li><a class="pagination-link is-current"
                                       aria-current="page">{{ transactions.number }}</a></li>
                                {% if transactions.has_next %}
                                    <li><a class="pagination-link" aria-label="Goto page 47"
                                           href="?page={{ transactions.next_page_number }}">Next</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        const host = window.location.host;
        const protocol = window.location.protocol;

        const currency_conversion_url = protocol + '//' + host + '/api/conversion';

        const currency_conversion = (amount, from, to) => {
            const url = currency_conversion_url + '/' + from + '/' + to + '/' + amount;
            return fetch(url)
                .then(response => response.json())
                .then(data => {
                    console.log(data);
                    return data;
                })
                .catch(error => {
                    console.log(error);
                });
        };

        const table_data_uuid = document.querySelectorAll('[data-uuid]');
        table_data_uuid.forEach(async (item) => {
            let uuid = item.getAttribute('data-uuid');
            const amount = item.innerText;
            const converted_amount = currency_conversion(amount, 'GBP', '{{ user.currency.code }}');
            converted_amount.then(
                (data) => {
                    item.innerText = data.converted_value;
                }
            ).catch((error) => {
                    console.log(error);
                }
            )
        });

        const balance = document.getElementById('balance');
        const converted_balance = currency_conversion(balance.innerText, 'GBP', '{{ user.currency.code }}');
        converted_balance.then((data) => {
            balance.innerText = data.converted_value;
        }).catch((error) => {
            console.log(error);
        });
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}
    <title>Home</title>
{% endblock %}

{% block content %}
    {% include 'side_nav.html' %}
    <div class="column">
        <div class="hero">
            <div class="hero is-info">
                <div class="hero-body">
                    <p class="title">
                        Hello there {{ user.username | capfirst }}!
                    </p>
                    <p class="subtitle">
                        {% if user.get_unread_notifications %}
                            You have {{ user.get_unread_notifications.count }} notifications.
                        {% else %}
                            You have no notifications.
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}
    <title>Sign Up</title>
{% endblock %}

{% block content %}
    <div class="column is-4 ml-auto mr-auto">
        <form method="post">
            {% csrf_token %}
            {% if error %}
                <div class="help is-danger">
                    <p>{{ error }}</p>
                </div>
            {% endif %}
            {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text }}</p>
                    {% endif %}
                    {% if field.field.widget.input_type == 'checkbox' %}
                        <div class="control">
                            <label class="checkbox">
                                <input type="checkbox" name="{{ field.name }}" {% if field.value %}checked{% endif %}
                                       class="input">
                                {{ field.label }}
                            </label>
                        </div>
                    {% elif field.field.widget.input_type == 'select' %}
                        <div class="select">
                            <select name="{{ field.name }}">
                                {% for choice in field.field.choices %}
                                    <option value="{{ choice.0 }}" {% if choice.0 == field.value %}selected{% endif %}>
                                        {{ choice.1 }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                    {% else %}
                        <div class="control">
                            <input type="{{ field.field.widget.input_type }}"
                                   name="{{ field.name }}"
                                    {% if field.value %}
                                   value="{{ field.value }}"
                                    {% endif %}
                                   class="input"
                                   id="{{ field.id_for_label }}">
                        </div>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="help is-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="field">
                <small class="is-info">
                    Not a member? <a href="{% url 'pay_app:register' %}">Sign Up</a>
                </small>
            </div>
            <div class="field">
                <div class="control">
                    <button type="submit" class="button is-link">Log In</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/notifications.html
{% extends 'base.html' %}
{% block title %}
    <title>Notifications</title>
{% endblock %}

{% block content %}
    {% include 'side_nav.html' %}
    <div class='column is-5 ml-auto mr-auto'>
        <ul class="list has-hoverable-list-items has-overflow-ellipsis">
            {% for item in notifications %}
                <li class='list-item mb-5'>
                    <div class="list-item-image">
                        <figure class="image is-48x48">
                            {% load static %}
                            <img class="is-rounded" src="{% static 'images/profile.jpg' %}" alt="">
                        </figure>
                    </div>

                    <div class="list-item-content">
                        <div class="list-item-title is-flex is-justify-content-space-between">
                            <span>{{ item.sender }}</span>
                            <span class="has-text-weight-normal has-text-grey">{{ item.date }}</span>
                        </div>
                        <div class="list-item-description">
                            {{ item.message }}
                        </div>
                    </div>

                    {% if item.transaction.money_from.id == user.id %}
                        <div class="list-item-controls is-hidden-mobile mt-2 ml-auto">
                            <div class="buttons">
                                <a class="button is-danger" href="{% url 'pay_app:reject-payment' item.id %}">
                                    <span class="icon"><i class="fas fa-times-square"></i></span>
                                </a>

                                <a class="button is-warning" href="{% url 'pay_app:notification' item.id %}">
                                    <span class="icon"><i class="fas fa-trash"></i></span>
                                </a>

                                <a class="button is-success" href="{% url 'pay_app:accept-payment' item.id %}">
                                    <span class="icon"><i class="fas fa-check-square"></i></span>
                                </a>
                            </div>
                        </div>
                    {% endif %}
                </li>
                <hr>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
    <title>Sign Up</title>
{% endblock %}

{% block content %}
    <div class="column is-4 ml-auto mr-auto">
        <form method="post">
            {% csrf_token %}
            {% if error %}
                <div class="help is-danger">
                    <p>{{ error.title }}</p>
                    <small>{{ error.message }}</small>
                </div>
            {% endif %}
            {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text }}</p>
                    {% endif %}
                    {% if field.field.widget.input_type == 'checkbox' %}
                        <div class="control">
                            <label class="checkbox">
                                <input type="checkbox" name="{{ field.name }}" {% if field.value %}checked{% endif %}
                                       class="input">
                                {{ field.label }}
                            </label>
                        </div>
                    {% elif field.field.widget.input_type == 'select' %}
                        <div class="select">
                            <select name="{{ field.name }}">
                                {% for choice in field.field.choices %}
                                    <option value="{{ choice.0 }}" {% if choice.0 == field.value %}selected{% endif %}>
                                        {{ choice.1 }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                    {% else %}
                        <div class="control">
                            <input type="{{ field.field.widget.input_type }}"
                                   name="{{ field.name }}"
                                    {% if field.value %}
                                   value="{{ field.value }}"
                                    {% endif %}
                                   class="input"
                                   id="{{ field.id_for_label }}">
                        </div>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="help is-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="field">
                <small class="is-info">
                    Already have an account? <a href="{% url 'pay_app:login' %}">Login</a>
                </small>
            </div>
            <div class="field">
                <div class="control">
                    <button type="submit" class="button is-link">Sign Up</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/request_payment.html
{% extends 'base.html' %}

{% block title %}
    <title>Request Payment</title>
{% endblock %}

{% block content %}
    {% include 'side_nav.html' %}
    <div class="column is-4 ml-auto mr-auto">
        <form method="post">
            {% csrf_token %}
            {% if error %}
                <div class="help is-danger">
                    {{ error }}
                </div>
            {% endif %}
            {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                    {% if field.help_text %}
                        <small class="help is-info">{{ field.help_text }}</small>
                    {% endif %}
                    {% if field.field.widget.input_type == 'checkbox' %}
                        <div class="control">
                            <label class="checkbox">
                                <input type="checkbox" name="{{ field.name }}" {% if field.value %}checked{% endif %}
                                       class="input">
                                {{ field.label }}
                            </label>
                        </div>
                    {% elif field.field.widget.input_type == 'select' %}
                        <div class="select">
                            <select name="{{ field.name }}">
                                {% for choice in field.field.choices %}
                                    <option value="{{ choice.0 }}" {% if choice.0 == field.value %}selected{% endif %}>
                                        {{ choice.1 }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                    {% else %}
                        <div class="control">
                            <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}"
                                   value="{{ field.value }}" class="input" id="{{ field.id_for_label }}">
                        </div>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="help is-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="field is-flex gap-1">
                <div class="control">
                    <button type="submit" class="button is-link">Send</button>
                </div>
                <div class="control">
                    <a href="{% url 'pay_app:index' %}" class="button is-link is-light">Cancel</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/send_money.html
{% extends 'base.html' %}

{% block title %}
    <title>Send Money</title>
{% endblock %}

{% block content %}
    {% include 'side_nav.html' %}
    <div class="column is-4 ml-auto mr-auto">
        <form method="post">
            {% csrf_token %}
            {% if error %}
                <div class="help is-danger">
                    {{ error }}
                </div>
            {% endif %}
            {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                    {% if field.help_text %}
                        <small class="help is-info">{{ field.help_text }}</small>
                    {% endif %}
                    {% if field.field.widget.input_type == 'checkbox' %}
                        <div class="control">
                            <label class="checkbox">
                                <input type="checkbox" name="{{ field.name }}" {% if field.value %}checked{% endif %}
                                       class="input">
                                {{ field.label }}
                            </label>
                        </div>
                    {% elif field.field.widget.input_type == 'select' %}
                        <div class="select">
                            <select name="{{ field.name }}">
                                {% for choice in field.field.choices %}
                                    <option value="{{ choice.0 }}" {% if choice.0 == field.value %}selected{% endif %}>
                                        {{ choice.1 }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                    {% else %}
                        <div class="control">
                            <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}"
                                   value="{{ field.value }}" class="input" id="{{ field.id_for_label }}">
                        </div>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="help is-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="field is-flex gap-1">
                <div class="control">
                    <button type="submit" class="button is-link">Send</button>
                </div>
                <div class="control">
                    <a href="{% url 'pay_app:index' %}" class="button is-link is-light">Cancel</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/side_nav.html
<div class="column is-2">
    <aside class="menu is-hidden-mobile is-flex is-flex-direction-column">
        <p class="menu-label">
            General
        </p>
        <ul class="menu-list" id="menu-list">
            <li><a href="{% url 'pay_app:dashboard' %}" id="dashboard">Dashboard</a></li>
            <li><a id="notifications" href="{% url 'pay_app:notifications' %}">Notifications <span class="notification-bubble">{{ user.get_unread_notifications.count }}</span></a></li>
            <li><a>Other</a>
                <ul>
                    <li><a href="{% url 'pay_app:request-payment' %}" id="pending_money">Request Payment</a></li>
                    {% if user.is_admin %}
                        <li><a href="" id="admin_view_transactions">All Site Transactions</a></li>
                    {% endif %}
                </ul>
            </li>
        </ul>
    </aside>
</div>
<script>
    // This is a workaround for the fact that Django is ssr.
    const menu_list = document.getElementById('menu-list');
    const menu_list_items = menu_list.querySelectorAll('li')
    const navbar = document.getElementById('navbar');

    menu_list_items.forEach((item) => {
        item.addEventListener('click', (e) => {
            const active_item_id = localStorage.getItem('active_item');

            if (active_item_id) {
                const active_item = document.getElementById(active_item_id);
                active_item.classList.remove('is-active');
                localStorage.removeItem('active_item');

                if (active_item_id === e.target.id) {
                    return;
                }

                localStorage.setItem('active_item', e.target.id);
            }

            e.target.classList.add('is-active');
            localStorage.setItem('active_item', e.target.id);
        });
    });

    const active_item_id = localStorage.getItem('active_item');
    if (active_item_id) {
        const active_item = document.getElementById(active_item_id);
        active_item.classList.add('is-active');
    }

    // if navbar is used for navigation remove active class from menu list
    navbar.addEventListener('click', (e) => {
        const active_item_id = localStorage.getItem('active_item');
        if (active_item_id) {
            const active_item = document.getElementById(active_item_id);
            active_item.classList.remove('is-active');
            localStorage.removeItem('active_item');
        }
    });
    
    window.addEventListener('beforeunload', (e) => {
        const active_item_id = localStorage.getItem('active_item');
        if (active_item_id) {
            const active_item = document.getElementById(active_item_id);
            active_item.classList.remove('is-active');
            localStorage.removeItem('active_item');
        }
    });
</script>

templates/transaction_successful.html
{% extends 'base.html' %}

{% block title %}
    <title>Transaction Successful</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Transaction Successful</h1>
                <p>Thank you for your payment. Your transaction has been completed, head to the <a
                        href="{% url 'pay_app:dashboard' %}">dashboard</a> to view details of this transaction.</p>
            </div>
        </div>
    </div>
{% endblock %}